[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
# TODO: check version of setuptools

[project]
name = "viperleed"
requires-python = ">=3.7"
dynamic = ["version"]
readme = "README.md"
dependencies = [
    "numpy",
    "wrapt",
    "quicktions",
    "scipy",
    "sklearn",
    "matplotlib",
    "psutil",
]

[project.license]
# TODO: add license information

[project.optional-dependencies]
GUI = [
    "PyQt5",
    "mplcairo"
]
hardware = [
    "requests"
]
dev = [
    "line_profiler",
    "sphinx"
]
