[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
# TODO: check version of setuptools

[project]
name = "viperleed"
dynamic = ["version"]
requires-python = ">=3.7"
readme = "README.md"
dependencies = [
    "fortranformat",
    "numpy",
    "wrapt",
    "quicktions",
    "scipy",
    "scikit-learn",
    "matplotlib",
    "psutil",
]

[project.optional-dependencies]
GUI = [
    "PyQt5",
    "mplcairo"
]
hardware = [
    "requests"
]
dev = [
    "line_profiler",
    "pytest",
    "sphinx"
]

[tools.setuptools.dynamic]
version = {attr = "viperleed.__version__"}


[tool.setuptools.packages.find]
exclude = [
    "tests",
    "doc",
    "dist",
    "calculations",
    "environments"
]