[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
# TODO: check version of setuptools

[project]
name = "viperleed"
dynamic = [
    "version",
    "readme",
    ]
requires-python = ">=3.7"
dependencies = [
    "fortranformat",
    "matplotlib",
    "numpy",
    "psutil",
    "quicktions",
    "scikit-learn",
    "scipy",
    "wrapt",
]

[project.optional-dependencies]
GUI = [
    "PyQt5",
]
GUI_optional = [
    "mplcairo",
]
hardware = [
    "requests"
]
dev = [
    "line_profiler",
    "pytest",
]
doc = [
    "myst-nb",
    "sphinx",
    "sphinxcontrib-bibtex",
    "sphinx_rtd_theme",
    "sphinxcontrib-spelling",
    "sphinxcontrib-svg2pdfconverter",
]

[tool.setuptools.dynamic]
version = {attr = "viperleed.__version__"}
readme = {file = "README.md"}


[tool.setuptools.packages.find]
exclude = [
    "tests",
    "doc",
    "dist",
    "calculations",
    "environments"
]